name: Issue and Dispatch Workflow

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Display Trigger
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Issue Action: ${{ github.event.action }}"
      - name: Show Actor
        run: |
          echo "Action performed by: $GITHUB_ACTOR"
